language: android
jdk: openjdk7
android:
  components:
    - build-tools-23.0.1
    - extra-android-m2repository
    - android-23
  licenses:
    - '.+'
before_install:
 - chmod +x gradlew
script:
  - ./gradlew build connectedCheck
